AllCops:
  Exclude:
    - './spec/fixtures/migrations/**/*.rb'
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - './spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false
